### PR TITLE
ci: add typo check in workflow.

### PR DESCRIPTION
**Pull request by zackshen**
### Description

typo check should be a regular step in workflow.

### Test Plan

nothing

### CODE REVIEW

**Comment by hyf0** [comment]
Cool. This is very useful. Let's how we could merge this PR.

**Comment by zackshen** [comment]
> Cool. This is very useful. Let's how we could merge this PR.

ok.

**Comment by zackshen** [comment]
Can this PR be merged? If continue to merge code into main branch, I must continue to maintain this PR, maybe some typo would happen。

I know the repository maintainer is very busy, but can help confirm whether it can be merged? Or have any other opinions?  Please @hyf0 

Is there a mechanism for handling issues, such as fixed reviewers?

**Comment by hyf0** [comment]
Sorry for the waitting. I will try merge it today.

**Comment by hyf0** [comment]
@zackshen Hi, you could leave this pr to me now. I'm doing some adjustment and will merge it latterly.

**Comment by zackshen** [comment]
> @zackshen Hi, you could leave this pr to me now. I'm doing some adjustment and will merge it latterly.

Sure.

**Review by hyf0 — APPROVED** [review]

**Pull request merged**
