### PR TITLE
feat(rust): use fast-glob instead of glob-match

### PR DESCRIPTION
**Pull request by shulaoda**
### Description
Related to https://github.com/web-infra-dev/rspack/pull/6668

At present, there are many problems with `glob-match`, and the author no longer maintains it. It is recommended to use `fast-glob`. You can check the README of [this repo](https://github.com/shulaoda/glob-match) for specific issues that exist.

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
Let me add forked repo benchmark, and see if it has any performance improvement.

**Comment by Boshen** [comment]
Why is the repo https://github.com/shulaoda/glob-match archived?

**Comment by IWANABETHATGUY** [comment]
> Why is the repo https://github.com/shulaoda/glob-match archived?

I think he mean this repo, https://github.com/shulaoda/fast-glob

**Comment by shulaoda** [comment]
I updated the README in `fast-glob`, and you can see specific issues which have been resolved in the fork repo `glob-match`.

**Pull request closed without merging**
