### PR TITLE
feat(cli): resolve `rolldown.config` by default when `-c` is unspecified

### LINKED ISSUE #3248: [Bug]: rolldown -c -w parse -w as config
### Reproduction link or steps

Repo: https://github.com/phk422/rolldown-demo
Running [pnpm dev](https://github.com/phk422/rolldown-demo/blob/76b9430664789c5c5f5908785a1e6329feff6e62/package.json#L8) works fine.
However, running [pnpm dev2](https://github.com/phk422/rolldown-demo/blob/76b9430664789c5c5f5908785a1e6329feff6e62/package.json#L9) results in an error.

### What is expected?

The rolldow.config configuration can be correctly identified using pnpm dev2

### What is actually happening?

The following error occurs with pnpm dev2:

```bash
> rolldown -c -w

Error: Error happened while loading config.
    at loadConfig (file:///D:/hk-project/rolldown-demo/node_modules/.pnpm/rolldown@1.0.0-beta.1/node_modules/rolldown/dist/esm/cli.mjs:352:9)
    at bundleWithConfig (file:///D:/hk-project/rolldown-demo/node_modules/.pnpm/rolldown@1.0.0-beta.1/node_modules/rolldown/dist/esm/cli.mjs:359:23)
    ... 4 lines matching cause stack trace ...
    at async importModuleDynamicallyWrapper (node:internal/vm/module:429:15) {
  [cause]: Error: Unsupported config format. Expected: `.js,.mjs,.cjs,.ts,.mts,.cts` but got ``
      at loadConfig (file:///D:/hk-project/rolldown-demo/node_modules/.pnpm/rolldown@1.0.0-beta.1/node_modules/rolldown/dist/esm/cli.mjs:350:12)
      at bundleWithConfig (file:///D:/hk-project/rolldown-demo/node_modules/.pnpm/rolldown@1.0.0-beta.1/node_modules/rolldown/dist/esm/cli.mjs:359:23)
      at main (file:///D:/hk-project/rolldown-demo/node_modules/.pnpm/rolldown@1.0.0-beta.1/node_modules/rolldown/dist/esm/cli.mjs:2004:9)
      at file:///D:/hk-project/rolldown-demo/node_modules/.pnpm/rolldown@1.0.0-beta.1/node_modules/rolldown/dist/esm/cli.mjs:2017:1
      at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
      at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
      at async importModuleDynamicallyWrapper (node:internal/vm/module:429:15)
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.17763
    CPU: (12) x64 Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
    Memory: 13.07 GB / 31.83 GB
  Binaries:
    Node: 18.19.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.33.6 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Internet Explorer: 11.0.17763.2989
  npmPackages:
    rolldown: 1.0.0-beta.1 => 1.0.0-beta.1
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by shulaoda**
### Description

Related to #3248

### CODE REVIEW

**Comment by underfin** [comment]
Could you add a test for it?

**Comment by phk422** [comment]
Thanks for this PR, but I don't think it solves the problem. It only addresses the default value issue for the configuration file. However, I believe the essence of the problem is that when using parseArgs, it treats the parameters following a string option as a string. For example, as mentioned in my issue, running `rolldown -c -w` will pass -w as the configuration file path.

**Comment by shulaoda** [comment]
> For example, as mentioned in my issue, running `rolldown -c -w` will pass -w as the configuration file path.

Yes, you're right. I will address it further.

**Comment by shulaoda** [comment]
It didn't solve the issue, but rather addressed another related problem.

**Review by underfin — APPROVED** [review]

**Pull request merged**
