### PR TITLE
perf(sourcemap): pre-allocate concat sourcemap builder

### PR DESCRIPTION
**Pull request by underfin**

### CODE REVIEW

**Review by hyf0 — APPROVED** [review]
Interesting. Any performance gain locally?

**Comment by underfin** [comment]
bundle/bundle@threejs10x-sourcemap
                        time:   [142.46 ms 143.12 ms 143.90 ms]
                        change: [−8.4670% −5.0458% −2.3010%] (p = 0.00 < 0.05)
                        Performance has improved.

**Comment by overlookmotel** [comment]
@underfin Any guess why this produces 5% speed-up locally, but no sign of a difference on CI benchmarks?

**Comment by underfin** [comment]
> @underfin Any guess why this produces 5% speed-up locally, but no sign of a difference on CI benchmarks?

I hasn't idea for it...

**Pull request merged**
