### PR TITLE
perf: avoid unnecessary allocation

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
### Description
1. Remove unnecessary memory allocation of `include_str!().to_string`

### CODE REVIEW

**Review by hyf0 — APPROVED** [review]

**Comment by hyf0** [comment]
I'm considering using https://docs.rs/arcstr/latest/arcstr/ to replace all usages of `Arc<str>` and `String`. Any suggestion?

**Comment by IWANABETHATGUY** [comment]
> I'm considering using https://docs.rs/arcstr/latest/arcstr/ to replace all usages of `Arc<str>` and `String`. Any suggestion?

I am not familiar with that crate, but it would worth trying if we use the extra feature of `arcstr`.

**Comment by Boshen** [comment]
It’s possible to create a const ArcStr from a literal via the [arcstr::literal!](https://docs.rs/arcstr/latest/arcstr/macro.literal.html) macro. This is probably the killer feature, to be honest.

These “static” ArcStrs are zero cost, take no heap allocation, and don’t even need to perform atomic reads/writes when being cloned or dropped (nor at any other time).

---

Seems like a good choice for this scenario.

**Comment by IWANABETHATGUY** [comment]
known issue of  WASI CI, directly merged

**Pull request merged**
