### PR TITLE
feat(rust): rendering runtime module in snapshot testing

### PR DESCRIPTION
**Pull request by hyf0**
### Test Plan

---

### CODE REVIEW

**Comment by hyf0** [comment]
Current dependencies on/for this PR:
* main
  * **PR #365** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/365?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #367** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/367?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #369** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/369?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #370** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/370?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #371** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/371?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #372** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/372?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #374** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/374?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #375** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/375?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
                  * **PR #377** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/377?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                    * **PR #378** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/378?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                      * **PR #379** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/379?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                        * **PR #380** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/380?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                          * **PR #381** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/381?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                            * **PR #382** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/382?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                              * **PR #383** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/383?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                * **PR #388** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/388?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rolldown-rs/rolldown/375?utm_source=stack-comment).

**Comment by underfin** [comment]
The runtime code is larger, it is difficult to review, maybe we can use another idea to exclude it. I see esbuild snapshot also hasn't runtime code.

**Comment by hyf0** [comment]
> The runtime code is larger, it is difficult to review, maybe we can use another idea to exclude it. I see esbuild snapshot also hasn't runtime code.

This tests the behaviors of treeshaking with runtime module. Feel free to open a team meeting to discuss this PR.

**Comment by underfin** [comment]
Track here https://github.com/rolldown-rs/rolldown/issues/390.

**Comment by underfin** [comment]
Other we need to add `tree shaking` option to enable the behaviors of treeshaking with module. You can do it at new pr.

**Review by underfin — APPROVED** [review]

**Comment by Boshen** [comment]
### Merge activity

* **Nov 26, 10:26 PM**: @Boshen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/rolldown-rs/rolldown/375).
* **Nov 26, 10:38 PM**: [Graphite](https://app.graphite.dev/github/pr/rolldown-rs/rolldown/375) couldn't merge this PR because it had conflicts with the trunk branch.

**Pull request merged**
