### PR TITLE
chore(rust/esbuild-tests): enable more test cases.

### PR DESCRIPTION
**Pull request by Cecil0o0**
### Description

`define_optional_chain_lowered` totally equal with `define_optional_chain`, I leave the latter?

### CODE REVIEW

**Comment by hyf0** [comment]
Neither define or TLA are supported. We aren't gonna enable these tests.

**Comment by Cecil0o0** [comment]
> Neither define or TLA are supported. We aren't gonna enable these tests.

Could I ask for reason Why we not to support TLA?

**Comment by hyf0** [comment]
TLA is not supported yet. We aren't saying not support TLA.

**Comment by Cecil0o0** [comment]
> TLA is not supported yet. We aren't saying not support TLA.

Got. Try to find other cases

**Pull request closed without merging**
