### PR TITLE
ci: move node-validation to seprate file

### PR DESCRIPTION
**Pull request by Dunqing**
### Description

`pnpm format:ci` will format Markdown files. but the ci action will ignore markdown changes. So I think we should do a lint check in the new action.
### Test Plan

---

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#584** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/584?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Dunqing and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by hyf0** [comment]
I get you. But the better solution would be removing `paths-ignore:` in `CI.yaml`. Due to the "Status check" of github is static and running these actions are required. We need to bare with useless action running for some PRs.

**Comment by hyf0** [comment]
> I get you. But the better solution would be removing `paths-ignore:` in `CI.yaml`. Due to the "Status check" of github is static and running these actions are required. We need to bare with useless action running for some PRs.

Or should we say the `path ignore `is not smart enough. It should treat skipped actions as completed successfully rather than skipped.

**Comment by Dunqing** [comment]
> I get you. But the better solution would be removing `paths-ignore:` in `CI.yaml`. Due to the "Status check" of github is static and running these actions are required. We need to bare with useless action running for some PRs.

CI action has many jobs, As far as I know only `node-validation` needs to remove path_ignores. but this causes all other jobs to be executed, so I moved it to a new action to avoid useless CI check

**Comment by hyf0** [comment]
> > I get you. But the better solution would be removing `paths-ignore:` in `CI.yaml`. Due to the "Status check" of github is static and running these actions are required. We need to bare with useless action running for some PRs.
> 
> CI action has many jobs, As far as I know only `node-validation` needs to remove path_ignores. but this causes all other jobs to be executed, so I moved it to a new action to avoid useless CI check

As I was saying, it's useless and we have to bare with it. You will notice that currently your PR doesn't not run `cargo test` action and it's required to merge this PR. The problem is that github can't set what actions are required dynamically, so we need to set needed actions required. That's where we hit the "path ignore" problem.

Skipped actions by "path ignore" won't pass the checks of github.

**Review by hyf0 — APPROVED** [review]
Let's merge this one first. I will refactor them using https://github.com/dorny/paths-filter later.

**Pull request merged**
