### PR TITLE
chore(deps): bump oxc to `0.19.0`

### PR DESCRIPTION
**Pull request by rzvxa**
You can read about the new builder methods here:
https://github.com/oxc-project/oxc/pull/3890

We also provide the `IntoIn` and `FromIn` in the `oxc_allocator` crate so I've removed the rolldown helper's version.

I didn't touch the snippets but now some of them can painlessly be replaced with builder methods since we accept generic arguments for things that can be allocated on the arena. So now you can pass `&str` where `Atom` or `&'ast str` is expected. Or pass in a stack ast type and have it boxed in the builder using `IntoIn` bounds.

### CODE REVIEW

**Comment by Boshen** [comment]
@rzvxa is a core contributor of oxc. 

This change is part of https://github.com/oxc-project/oxc/issues/3819 where we generate all ast related code with automation.

The next step is https://github.com/oxc-project/backlog/issues/184, where we generate template code via macros. Please advise us in the issue if there are future code patterns that we need to support.

**Review by hyf0 — APPROVED** [review]
Nice!

**Comment by IWANABETHATGUY** [comment]
Thanks!!

**Comment by rzvxa** [comment]
Is there anything wrong? Let me know if there are any changes that I need to make.

**Comment by hyf0** [comment]
> Is there anything wrong? Let me know if there are any changes that I need to make.

Nope. It's just the wasm test on windows sometimes will be broken. It's a known problem.

**Pull request merged**
