### PR TITLE
feat(rolldown): support compile to wasi

### LINKED ISSUE #832: WASI support
Ref: https://github.com/rolldown/rolldown/pull/810

Wasi target is almost done except some problems. They show up on different machines:

Machine of @hyf0 
- Any `std::fs::xxx` call blocks the whole program and make the program hang.
- `rayon` could not work, so all `par_xxc` calls needs to be removed.
- Process hung instead exit successfully after bundling.

Machine of @Brooooooklyn 
- Any `std::fs::xxx` call blocks the whole program and make the program hang.
  - Add an extra `std::fs::xxx` call in the beginning of the program solves the problem but doesn't works on @hyf0.
- Unknown segmentation fault.
- Process hung instead exit successfully after bundling.

Related refs:
- https://github.com/oxc-project/oxc-resolver/pull/124
- #834
- #840
- #872

### PR DESCRIPTION
**Pull request by Brooooooklyn**
This pull request is working on adding a wasi compile target for the rolldown itself.

### CODE REVIEW

**Comment by Brooooooklyn** [comment]
Test with this branch, you can run the following commands:

- `rustup target add wasm32-wasi-preview1-threads`
- `pnpm --filter=rolldown build-binding:release --target wasm32-wasi-preview1-threads`
- `pnpm --filter=rolldown build-node `
- `NAPI_RS_FORCE_WASI=1 pnpm --filter=@example/basic build`

There is a weird error at this moment:

```text
Error [RuntimeError]: unreachable
    at rust_panic (wasm://wasm/0b2ab492:wasm-function[4980]:0x31a06b)
    at _ZN3std9panicking20rust_panic_with_hook17h3f09aea7b2ed8bbbE (wasm://wasm/0b2ab492:wasm-function[313]:0x37887)
    at _ZN3std9panicking19begin_panic_handler28_$u7b$$u7b$closure$u7d$$u7d$17ha537cf0f5d20bf0bE (wasm://wasm/0b2ab492:wasm-function[5000]:0x31b198)
    at _ZN3std10sys_common9backtrace26__rust_end_short_backtrace17h9f64aa6f1c5a364cE (wasm://wasm/0b2ab492:wasm-function[4999]:0x31b0fe)
    at rust_begin_unwind (wasm://wasm/0b2ab492:wasm-function[1226]:0xe85e5)
    at _ZN4core9panicking9panic_fmt17h02a8c9b024bafa78E (wasm://wasm/0b2ab492:wasm-function[67]:0x3dd1)
    at _ZN5alloc7raw_vec17capacity_overflow17h8b23895888f87993E (wasm://wasm/0b2ab492:wasm-function[71]:0x40a8)
    at _ZN12oxc_resolver25ResolverGeneric$LT$Fs$GT$15load_extensions17hb54a1cb9ebda3a08E (wasm://wasm/0b2ab492:wasm-function[173]:0x15afa)
    at _ZN12oxc_resolver25ResolverGeneric$LT$Fs$GT$12load_as_file17ha8065311eab60283E (wasm://wasm/0b2ab492:wasm-function[175]:0x162ca)
    at _ZN12oxc_resolver25ResolverGeneric$LT$Fs$GT$25load_as_file_or_directory17h2b59a006b80b355cE (wasm://wasm/0b2ab492:wasm-function[230]:0x24da9)

Node.js v20.11.1
/home/lyn/workspace/github/rolldown/examples/basic-vue:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @example/basic@ build: `node build.js`
Exit status 1
```

**Comment by Brooooooklyn** [comment]
* **#467** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/467?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Brooooooklyn and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by hyf0 — DISMISSED** [review]
Cool!

**Review by hyf0 — APPROVED** [review]
Cooler!

**Pull request merged**
