### PR TITLE
docs: Add architecture doc

### PR DESCRIPTION
**Pull request by ericyd**
### Description

This PR adds an Architecture doc. The purpose of this doc is to describe the high level architecture of the rolldown crate.

▶️ **[Rendered doc](https://github.com/ericyd/rolldown/blob/architecture-docs/web/docs/contrib-guide/architecture.md)** ◀️
(ignore the script src at the top)

Notably, this PR adds a Mermaid component to the documentation site. This has a client-side rendering requirement, which might be undesirable. An alternative approach could be to render the mermaid diagrams to SVG at build time, and link to the pre-built images for the production build, as suggested in [this comment to a similar issue](https://github.com/vuejs/vitepress/issues/2538#issuecomment-1665435278).

This document is not complete, but rather a starting point which should be built on. There are still many parts of the rolldown code which are not clear to me and could be better explained. I'm choosing to open the PR now to get preliminary feedback from maintainers on the style and content of this doc. I'm not convinced this document is at a level of maturity that it adds value to this project. I have no ego attached to this and fully respect the decision to close this PR rather than merge it.

### CODE REVIEW

**Comment by hyf0** [comment]
Nice!

**Comment by hyf0** [comment]
Don't worry about the conflicts. I need some time to adjust the content. Once it's done, I' ll solve the conflict and merge it.

**Comment by ericyd** [comment]
Thanks @hyf0, I'm happy to take any feedback too and make adjustments, whatever is more convenient for you.

**Comment by ericyd** [comment]
No bad feelings on my part, but I've decided to close this PR for a few reasons:

1. I'm not even sure what is written here is still accurate, and I don't have time to double check
2. I thought I'd have more time to dive into this, but without more guidance from maintainers I don't know how to do that effectively with my available time
3. Leaving this open is inevitably causing cognitive load for the maintainers, which is the opposite of my intention.
4. As stated in the PR description, I'm not convinced this doc was ever at a point of maturity where it actually contributed to the codebase.

I'll keep an eye on the project and hopefully be able to contribute in the future. In the meantime, I'd be happy to attempt to write more docs if that feels useful for any of the maintainers.

**Pull request closed without merging**
