### PR TITLE
fix: the crate rolldown_ecmascript's test can't pass

### LINKED ISSUE #1671: The crate rolldown_ecmascript's test can't pass
### Reproduction link or steps

cargo test -p rolldown_ecmascript

### What is expected?

image

### What is actually happening?

image

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13600KF
    Memory: 17.46 GB / 31.81 GB
  Binaries:
    Node: 18.20.4 - D:\Github\nvm\nodejs\node.EXE
    npm: 10.7.0 - D:\Github\nvm\nodejs\npm.CMD
    pnpm: 9.5.0 - D:\Github\nvm\nodejs\pnpm.CMD
    bun: 1.1.20 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (126.0.2592.81)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    rolldown: workspace:* => 0.12.1
```

### Any additional comments?

Related to #1670 

https://github.com/shulaoda/rolldown/blob/ea3837322a05386bf34526a3a12ec0a42c9acdad/crates/rolldown_ecmascript/Cargo.toml#L15-L23

### PR DESCRIPTION
**Pull request by shulaoda**
### Description
Closed #1671

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
Also if you make sure your pull request fixed some issues, you could write `fixed #xxx` rather than `related to #xxx`, more details you could refer https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by IWANABETHATGUY** [comment]
I think adding `os` feature in `Cargo.toml` under  `rolldown_resolver` directory should be more suitable.

**Review by IWANABETHATGUY — APPROVED** [review]
Thanks

**Comment by shulaoda** [comment]
> Thanks

but why ci is error？

**Pull request merged**
