### PR TITLE
perf(rolldown): generate unique span by decrementing u32::MAX

### PR DESCRIPTION
**Pull request by Boshen**
We assume

* newly inserted span is always empty (`(0, 0)`)
* it is unlikely that a span is at `u32::MAX`

### CODE REVIEW

**Comment by Boshen** [comment]
No performance change? And where is codspeed?

**Comment by IWANABETHATGUY** [comment]
image,  looks like it is already uploaded.
Don't know why not display as a comment

image

**Comment by Boshen** [comment]
image

**Comment by Boshen** [comment]
We have a very stupid thing:

https://github.com/oxc-project/oxc/blob/46b641b75d9da1ad1c3a0dd589766956880a583f/crates/oxc_span/src/span/mod.rs#L348-L352

```
impl Hash for Span {
    fn hash<H: Hasher>(&self, _state: &mut H) {
        // hash to nothing so all ast spans can be comparable with hash
    }
}
```

We need to make some changes in places where we need to hash the span in rolldown ...

**Pull request closed without merging**
