### PR TITLE
chore(rolldown): oxc v0.39.0

### PR DESCRIPTION
**Pull request by Boshen**

### CODE REVIEW

**Comment by Boshen** [comment]
Found a incorrect test 

```
---- fixture_with_config_tests__rolldown__topics__deconflict__decl_nested_assign_pattern__config_json stdout ----
Input: /Users/boshen/github/rolldown/crates/rolldown/tests/rolldown/topics/deconflict/decl_nested_assign_pattern/_config.json
```

```
✘ [ERROR] Multiple exports with the same name "baz"

    <stdin>:7:9:
      7 │ export { baz, baz2 }
        ╵          ~~~

  The name "baz" was originally exported here:

    <stdin>:3:29:
      3 │ export const { foo: { bar: { baz = '' } = {} } = {} } = { foo: { ba...
        ╵     
```

**Comment by Boshen** [comment]
@IWANABETHATGUY can you review the diffs before I make a release.

**Comment by Boshen** [comment]
> ## [CodSpeed Performance Report](https://codspeed.io/rolldown/rolldown/branches/oxc-0.39.0)
> ### Merging #3031 will **improve performances by 7.22%**
> Comparing `oxc-0.39.0` ([7656a91](https://github.com/rolldown/rolldown/commit/7656a9131cc5ac717740239fbad75f5162c2c611)) with `main` ([176666f](https://github.com/rolldown/rolldown/commit/176666fa328cf77657addaa04787061e9ac836b1))
> 
> ### Summary
> `⚡ 2` improvements `✅ 19` untouched benchmarks
> 
> ### Benchmarks breakdown
> Benchmark	`main`	`oxc-0.39.0`	Change
> ⚡	`bundle@rome-ts-minify`	929.5 ms	876.3 ms	+6.07%
> ⚡	`bundle@threejs10x-minify`	4.2 s	3.9 s	+7.22%

Minification performance is improved by fusing ast passes in oxc minifier.

**Comment by IWANABETHATGUY** [comment]
Most of the diff because we don't Unique `ThisExpr` which is generated by `GlobalDefineReplace`, no blocker, feel free to make a new release

**Comment by Boshen** [comment]
```
warning[advisory-not-detected]: advisory was not encountered
   ┌─ /home/runner/work/rolldown/rolldown/deny.toml:71:12
   │
71 │ ignore = ["RUSTSEC-2024-0388", "RUSTSEC-2024-0384"]
   │            ━━━━━━━━━━━━━━━━━ no crate matched advisory criteria
```

Issue in main.

**Review by hyf0 — APPROVED** [review]

**Pull request merged**
