### PR TITLE
chore: oxc_resolver v2.1.1

### PR DESCRIPTION
**Pull request by Boshen**
I made some performance improvements, creating a PR to see if there are any observable changes.

The upgrade also fixes a few crashes under windows. https://github.com/oxc-project/oxc-resolver/releases

### CODE REVIEW

**Comment by Boshen** [comment]
Feels like noise 🤔

**Comment by IWANABETHATGUY** [comment]
let's run again

**Comment by Boshen** [comment]
Ahh I don't know what's happening, let's just merge it ...

**Comment by hyf0** [comment]
The regression seems quite stable. Maybe should try it locally?

Codesped doesn't show regression, so I guess the cpu instructions doesn't increase.

**Review by hyf0 — APPROVED** [review]

**Comment by hyf0** [comment]
Let's merge it first to ensure correctness.

**Pull request merged**
