### PR TITLE
fix: add identifier for export default function without identifer

### PR DESCRIPTION
**Pull request by underfin**
### Description

The pr fixed some error with esm wrapped codegen and enable some esbuild passed test.
- add identifier for export default function without identifier
- avoid source mutation caused syntax error
```.ts
export default class Foo {} Foo.prop = 123
// before
var Foo = class Foo {} Foo.prop = 123  // syntax error
// pr
var Foo = class Foo {}\n Foo.prop = 123 // add `\n` to avoid error
```

### Test Plan
added.

---

### CODE REVIEW

**Comment by hyf0** [comment]
on hold for CR

**Comment by hyf0** [comment]
> ```ts
> export default class Foo {} Foo.prop = 123
> var Foo class Foo {}; Foo.prop = 123 // add `;` to avoid error
> ```

This looks confusing and invalid. What it means?

**Comment by underfin** [comment]
I updated at description

**Comment by hyf0** [comment]
@underfin  Are `export default class Foo`  being renamed to `var Foo = class Foo` expected? or just a temporary workaround?

**Comment by underfin** [comment]
Esbuild will codegen `class Foo{}`  to `var Foo = class {}`, it is equals to `var Foo = class Foo{}`, so here not removed `Foo`.

**Review by hyf0 — APPROVED** [review]

**Pull request merged**
