### PR TITLE
chore(rolldown): use bounded channel to avoid dynamic memory allocation

### PR DESCRIPTION
**Pull request by Brooooooklyn**

### CODE REVIEW

**Comment by Brooooooklyn** [comment]
* **#872** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/872?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Brooooooklyn and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by hyf0** [comment]
Do we do this only for supporting wasi? Unounded channel is not usable in wasi target?

**Review by hyf0 — APPROVED** [review]

**Comment by Brooooooklyn** [comment]
Benchmark shows it slower than the `UnboundedChannel`, I'll take a look

**Comment by hyf0** [comment]
> Benchmark shows it slower than the `UnboundedChannel`, I'll take a look

Could be just noise. I also benchmark it locally. Seems fine.

**Pull request merged**
