### PR TITLE
refactor: use unwrap_or_else

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
### Description
1. see the doc: https://doc.rust-lang.org/std/option/enum.Option.html#method.unwrap_or

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
* **#2871** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/2871?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/2871?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by shulaoda** [comment]
Is there any benefit of using `unwrap_or_else` over `unwrap_or`? I changed it originally because I thought `unwrap_or_else` has an extra closure.

**Comment by shulaoda** [comment]
> Is there any benefit of using `unwrap_or_else` over `unwrap_or`? I changed it originally because I thought `unwrap_or_else` has an extra closure.

I see, `unwrap_or` will result in additional calculations.

**Comment by hyf0** [comment]
Wonder why clippy didn't catch this.

**Review by hyf0 — APPROVED** [review]

**Comment by IWANABETHATGUY** [comment]
Currious either.

**Pull request merged**
