### PR TITLE
refactor(rust): add `SymbolNameRefToken` instead of abusing `SymbolRef`

### PR DESCRIPTION
**Pull request by hyf0**

### CODE REVIEW

**Comment by hyf0** [comment]
* **#2449** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/2449?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2448** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/2448?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2447** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/2447?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2446** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/2446?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hyf0 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by IWANABETHATGUY** [comment]
Any reason and benefit? `SynbolRef` could copy and `SymbolNameRefToken` is `Clone` .

**Comment by IWANABETHATGUY** [comment]
Also you will double the memory usage when store them.

**Comment by hyf0** [comment]
> Any reason and benefit? `SynbolRef` could copy and `SymbolNameRefToken` is `Clone` .

`ExternalModule` doesn't have a `SymbolRefDb` because it doesn't have AST in the first place. And we need a way to render a conflict name in the output, that's what `SymbolNameRefToken` for.

**Comment by hyf0** [comment]
The main purpose is to remove these hacky code: https://github.com/rolldown/rolldown/blob/e5c8b2fc1803e922e41b7a259c23078d545e2fb7/crates/rolldown/src/module_loader/module_loader.rs#L174-L178.

> Also you will double the memory usage when store them.

I think is fine so far. We won't create many instances due to its usage. There are also ways to optimize it, but doing right would be the first thing to do.

**Review by IWANABETHATGUY — APPROVED** [review]

**Pull request merged**
