### PR TITLE
feat: add entryFileNames, chunkFileNames for js normalizeOutputOptions

### LINKED ISSUE #775: Add js side `entryFileNames` `chunkFileNames` output options.
[Here](https://github.com/rolldown/rolldown/blob/main/packages/rolldown/src/options/output-options.ts#L60) not passs `entryFileNames` `chunkFileNames` to rust side.

### PR DESCRIPTION
**Pull request by PengBoUESTC**
### Description

for issue https://github.com/rolldown/rolldown/issues/775

### CODE REVIEW

**Comment by PengBoUESTC** [comment]
#775

**Comment by hyf0** [comment]
Please run `just roll` locally and fix the linting problems.

**Comment by PengBoUESTC** [comment]
> Please run `just roll` locally and fix the linting problems.

done

**Review by hyf0 — APPROVED** [review]

**Comment by hyf0** [comment]
Thank you!

**Pull request merged**
