### PR TITLE
feat: basic warning mechanism

### LINKED ISSUE #331: Support for warning mechanism

### PR DESCRIPTION
**Pull request by hyf0**
### Description

Closes #331

How it looks like: https://github.com/rolldown-rs/rolldown/blob/1019fc02a64be334b3b11f9552da96b2ced7d2ba/crates/rolldown/tests/fixtures/warnings/basic/artifacts.snap 

### Test Plan

---

### CODE REVIEW

**Comment by hyf0** [comment]
Current dependencies on/for this PR:
* main
  * **PR #315** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/315?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #316** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/316?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #317** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/317?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #319** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/319?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #320** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/320?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #321** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/321?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #322** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/322?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #323** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/323?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                  * **PR #324** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/324?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                    * **PR #325** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/325?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                      * **PR #326** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/326?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                        * **PR #327** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/327?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                          * **PR #328** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/328?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                            * **PR #329** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/329?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                              * **PR #332** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/332?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rolldown-rs/rolldown/332?utm_source=stack-comment).

**Comment by milesj** [comment]
What's the reasoning for not using miette's built in diagnostic stuff?

**Comment by hyf0** [comment]
> What's the reasoning for not using miette's built in diagnostic stuff?

Let me try to explain. What miette does/The main part it's allow to make diagnostics using dsl/macros. Macros has many limitations. And the expected of `miette` is "Write a unique error and use miette to declared a diagnostic", while we actually don't create diagnostic for each error.

In fact we currently have only one error with different error kind, this kind of breaks what miette expected.

Other than that, for supporting warnings, we need to display different contents/colors than errors, while miette is designed to work with errors and prefer macros. Maybe we could figure out a way to config it, But than I thought it's probably the same we use `ariadne` directly, since miette use it under the hood.

**Review by underfin — APPROVED** [review]

**Comment by hyf0** [comment]
### Merge activity

* **Nov 20, 1:16 AM**: @hyf0 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/rolldown-rs/rolldown/332).
* **Nov 20, 1:17 AM**: [Graphite](https://app.graphite.dev/github/pr/rolldown-rs/rolldown/332) rebased this pull request as part of a merge.
* **Nov 20, 1:19 AM**: @hyf0 merged this pull request with [Graphite](https://app.graphite.dev/github/pr/rolldown-rs/rolldown/332).

**Pull request merged**
