### PR TITLE
feat: rename vitest.config.ts to avoid warning; add empty caseConfig …

### PR DESCRIPTION
**Pull request by PengBoUESTC**
…warning info

### Description
- rename `vitest.config.ts` to avoid warning 
https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated

- add empty caseConfig warning 

### Test Plan

---

### CODE REVIEW

**Review by hyf0 — APPROVED** [review]
Thanks

**Comment by hyf0** [comment]
Run `just fmt` to fix all linting problems.

**Comment by PengBoUESTC** [comment]
> just fmt

done

**Review by hyf0 — APPROVED** [review]
Thank you!

**Pull request merged**
