### PR TITLE
chore: 🤖 improve rust fmt

### LINKED ISSUE #62: Improve Rustfmt
See https://github.com/web-infra-dev/oxc/blob/main/rustfmt.toml

Let's use `use_small_heuristics = "Max"`, my experience is that it provides the best readability. This also aligns with rustc.

You may also copy more from https://github.com/rust-lang/rust/blob/ddef56d5dfa18f169af9db912dc8e8343797eebb/rustfmt.toml#L3

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
### Description
Closed https://github.com/rolldown-rs/rolldown/issues/62

### Test Plan

---

### CODE REVIEW

**Review by hyf0 — APPROVED** [review]
LGTM. You could make the CI passed and merge the PR without approving.

**Comment by hyf0** [comment]
Please use `squash` to merge the PR next time.

**Comment by IWANABETHATGUY** [comment]
ok

**Comment by IWANABETHATGUY** [comment]
Can we set the squash by default?

**Pull request merged**
