### PR TITLE
fix: external module splitting case

### PR DESCRIPTION
**Pull request by underfin**
### Test Plan

---

### CODE REVIEW

**Comment by underfin** [comment]
Current dependencies on/for this PR:
* main
  * **PR #350** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/350?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rolldown-rs/rolldown/350?utm_source=stack-comment).

**Comment by hyf0** [comment]
#351 should fix this problem.

**Comment by underfin** [comment]
I'm not sure your fix is correct. Could add the test into test cases?

**Comment by hyf0** [comment]
> I'm not sure your fix is correct. Could add the test into test cases?

Done. https://github.com/rolldown-rs/rolldown/pull/351/commits/6f4d72b0ffa7343540e6c6e1ceda7f034bd4b4d7

**Pull request closed without merging**
