### PR TITLE
feat(rust): add `print` in `OxcCompiler`

### PR DESCRIPTION
**Pull request by hyf0**
### Test Plan

---

### CODE REVIEW

**Comment by hyf0** [comment]
Current dependencies on/for this PR:
* main
  * **PR #281** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/281?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rolldown-rs/rolldown/281?utm_source=stack-comment).

**Comment by Boshen** [comment]
Why do we need codegen again?

**Comment by hyf0** [comment]
> Why do we need codegen again?

We plan to add some pre-transpile operations for some thing like contestants folding. After transpiling, we need to transform the ast to string, and use the string as the input for bundling. This make sure the ast rolldown scans have no inconsistency between the ast and the source code.

**Comment by Boshen** [comment]
> > Why do we need codegen again?
> 
> We plan to add some pre-transpile operations for some thing like contestants folding. After transpiling, we need to transform the ast to string, and use the string as the input for bundling. This make sure the ast rolldown scans have no inconsistency between the ast and the source code.

Thanks! So this is preparation for the transformer.

**Comment by hyf0** [comment]
> > > Why do we need codegen again?
> > 
> > 
> > We plan to add some pre-transpile operations for some thing like contestants folding. After transpiling, we need to transform the ast to string, and use the string as the input for bundling. This make sure the ast rolldown scans have no inconsistency between the ast and the source code.
> 
> Thanks! So this is preparation for the transformer.

Yeah. Many transform functionality require this. TypeScript, JSX and so on. Also for some internal plugins using oxc, rolldown  only support passing around string between transform hooks, which also requires this.

**Review by underfin — APPROVED** [review]

**Pull request merged**
