### PR TITLE
feat: compose addon hooks

### LINKED ISSUE #1999: [Feature Request]: Support `banner`, `footer`, `intro` and `outro` for composejs plugin
### What problem does this feature solve?

Making `banner`, `footer`, `intro` and `outro` composable for compose js plugin
for now, these hook will bailout https://github.com/rolldown/rolldown/blob/1b49ed1102469e42283b38fa115cfb215bf25629/packages/rolldown/src/utils/compose-js-plugins.ts#L10-L28
### What does the proposed API look like?

n/a

### PR DESCRIPTION
**Pull request by ikkz**
resolves #1999

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
Can you double-check the implementation? It did not compose at all.

**Comment by ikkz** [comment]
> Can you double-check the implementation? It did not compose at all.

I added some log [here](https://github.com/rolldown/rolldown/blob/main/packages/rolldown/src/utils/normalize-input-options.ts#L16) 

image

and output of `just test-node rolldown -t "multi-addon-composing"`:

image

It seems that the 8 test plugins have been composed to 1 plugin.

Did I misunderstand this issue?

**Comment by IWANABETHATGUY** [comment]
> plugins

It's my mistake, we need a technique to determine if the plugin is composed, I am working on that.

**Comment by IWANABETHATGUY** [comment]
Can you add a test like https://github.com/rolldown/rolldown/pull/2008/files#diff-e709cc275fbba560e8cd300f426f59152876a8ce9c02bf8283a61fdc258cf319, so we could verify it is correctly composed

**Comment by ikkz** [comment]
> Can you add a test like https://github.com/rolldown/rolldown/pull/2008/files#diff-e709cc275fbba560e8cd300f426f59152876a8ce9c02bf8283a61fdc258cf319, so we could verify it is correctly composed

Done

**Review by IWANABETHATGUY — APPROVED** [review]
thanks

**Pull request merged**
