### PR TITLE
chore: remove unnecessary clippy allow directives

### PR DESCRIPTION
**Pull request by lzt1008**
### Description

This PR addresses the removal of unnecessary clippy::allow directives.

Changes are just remove the `#[allow(clippy::...)]` and unnecessary cast.

### CODE REVIEW

**Comment by hyf0** [comment]
Some changes changed the semantic of the original code. So this PR would be not accepted. Please split the change that removing unnecessary clippy directives to another PR.

**Comment by lzt1008** [comment]
> Some changes changed the semantic of the original code. So this PR would be not accepted. Please split the change that removing unnecessary clippy directives to another PR.

semantic changes are removed, now this PR only contains removal of unnecessary clippy allow and a unnecessary cast.

**Comment by Boshen** [comment]
How did you discover these problems? We may be able to enforce a rule for the future.

**Review by hyf0 — APPROVED** [review]
Thanks

**Comment by lzt1008** [comment]
> How did you discover these problems? We may be able to enforce a rule for the future.

I just discovered these unnecessary clippy::allow directives by accident and manually find it all. Currently, there isn't an automated rule in place for identifying these unnecessary Clippy allows(see rust-lang/rust-clippy/issues/3122). Hopefully, we'll see this as a clippy rule implemented soon.

**Pull request merged**
