### PR TITLE
refactor(rolldown_sourcemap): remove unused `Send` constraint

### PR DESCRIPTION
**Pull request by hyf0**

### CODE REVIEW

**Comment by hyf0** [comment]
* **#2597** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/2597?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2596** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/2596?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2595** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/2595?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2594** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/2594?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2593** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/2593?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2592** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/2592?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hyf0 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by IWANABETHATGUY — APPROVED** [review]

**Comment by IWANABETHATGUY** [comment]
For the title do you mean `unused`?

**Comment by hyf0** [comment]
> For the title do you mean `unused`?

Yeah. Typo

**Comment by hyf0** [comment]
### Merge activity

* **Nov 5, 4:32 AM EST**: [Graphite](https://app.graphite.dev/github/pr/rolldown/rolldown/2594) rebased this pull request after merging its parent, because this pull request is set to merge when ready.

**Pull request merged**
