### PR TITLE
feat: add native plugin example in rust

### PR DESCRIPTION
**Pull request by hyf0**
### Description

This PR is the first part of how to write a native plugin for rolldown and expose it in node binding.

### Test Plan

---

### CODE REVIEW

**Comment by hyf0** [comment]
Current dependencies on/for this PR:
* main
  * **PR #262** <a href="https://app.graphite.dev/github/pr/rolldown-rs/rolldown/262?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rolldown-rs/rolldown/262?utm_source=stack-comment).

**Comment by underfin** [comment]
https://github.com/rolldown-rs/rolldown/pull/261 I think the plugin could be a good example?

**Comment by hyf0** [comment]
> #261 I think the plugin could be a good example?

Yeah. I look into it and found out that it's too unique to be an general purpose example.

Since it's for vite only, the way users use it and how we publish it is most likely different from the native plugins for general purpose that rolldown provide.

**Comment by underfin** [comment]
It is a empty crate and unused, maybe adding it to development-native-plugin-guide is better?

**Comment by hyf0** [comment]
> It is a empty crate and unused, maybe adding it to development-native-plugin-guide is better?

Thanks for the suggestion. Sorry I don't add many contexts, it's going to be used in the future.

It's part of how to write a native plugin for rolldown and expose it in node binding.

**Review by underfin — APPROVED** [review]

**Pull request merged**
