### PR TITLE
feat(rust): move `string_wizard` to the repo

### PR DESCRIPTION
**Pull request by hyf0**
### Description

To have a quick development loop, it's better to move the `string_wizard` in the repo so we could modify it in time.

### CODE REVIEW

**Comment by hyf0** [comment]
* **#2573** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/2573?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2572** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/2572?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hyf0 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by IWANABETHATGUY** [comment]
I remember that you said that https://github.com/rolldown/rolldown/pull/1364#issuecomment-2165146752, maybe we should discuss it in the meeting.

**Comment by hyf0** [comment]
> I remember that you said that [#1364 (comment)](https://github.com/rolldown/rolldown/pull/1364#issuecomment-2165146752), maybe we should discuss it in the meeting.

Feel free to add this in discussion section.

**Comment by hyf0** [comment]
### Merge activity

* **Nov 3, 10:15 AM EST**: [Graphite](https://app.graphite.dev/github/pr/rolldown/rolldown/2572) disabled "merge when ready" on this PR due to: a merge conflict with the target branch; resolve the conflict and try again..

**Review by IWANABETHATGUY — APPROVED** [review]

**Pull request merged**
