### PR TITLE
refactor(rust): limit usages of oxc `Atom`

### PR DESCRIPTION
**Pull request by hyf0**
### Test Plan

---

### CODE REVIEW

**Comment by hyf0** [comment]
* **#574** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/574?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hyf0 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by overlookmotel** [comment]
@hyf0 Would it be helpful if we added a method in Oxc `Atom<'a>::new_in` which takes a `&str` + an `oxc_allocator::Allocator`?

If you're planning on doing more refactoring, then I think it could be a good idea. Once the inline optimization is implemented in `Atom`, for short strings `Atom::new` / `Atom::new_in` will copy the source string directly into its inline bytes, whereas building an `oxc_allocator::String` first will result in 2 copies - copy into the arena, then copy again into inline representation.

By the way `Atom::Arena(s)` no longer exists in latest Oxc, replaced by `Atom::new`. Sorry for all the churn! We think we've finally got there now with the API...

**Comment by hyf0** [comment]
This PR is only for integrating with `Atom` must have bound to a lifetime. So where to construct it become important. We need limit the constructing to a certain scope, so it won't affect other code.

> If you're planning on doing more refactoring

Yeah. Prabably no big one. But change `Atom::Arena(s)` to `Atom::new` will definitely do.

> , for short strings Atom::new / Atom::new_in will copy the source string directly into its inline bytes

Yeah. This would be helpful.

> By the way Atom::Arena(s) no longer exists in latest Oxc,

Got it. That's what this PR for. This PR makes that updating to latest oxc only need to change few code, otherwise we need do what this PR do in the updating PR too.

**Comment by overlookmotel** [comment]
Thanks for coming back. OK cool, seems like no hurry then. We can leave it until inline optimization is implemented. I just didn't want you to have to make loads of changes now, and then make them all over again later. But sounds like that's not going to happen.

**Pull request merged**
