### PR TITLE
feat: watch include exclude

### PR DESCRIPTION
**Pull request by underfin**
### Description

ref https://rollupjs.org/configuration-options/#watch-exclude

### CODE REVIEW

**Review by hyf0 — APPROVED** [review]

**Comment by IWANABETHATGUY** [comment]
Seems the watcher still has some unstable issues https://github.com/rolldown/rolldown/actions/runs/11456512537/job/31874824001

**Comment by underfin** [comment]
> Seems the watcher still has some unstable issues https://github.com/rolldown/rolldown/actions/runs/11456512537/job/31874824001

Yeah. Let us track it at here. https://github.com/rolldown/rolldown/issues/2438

**Comment by IWANABETHATGUY** [comment]
It seems the Windows ci panic could be reproduced stably

**Comment by underfin** [comment]
Look like the error is gone

**Pull request merged**
