### PR TITLE
refactor: improve logic of  `render_preliminary_assets` and add more comments

### PR DESCRIPTION
**Pull request by hyf0**

### CODE REVIEW

**Comment by hyf0** [comment]
* **#1624** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/1624?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1622** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/1622?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hyf0 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by hyf0** [comment]
@underfin The panic is caused here.

https://github.com/rolldown/rolldown/blob/24078fb0d2e060d5c51f6c5d82b569139d886320/crates/rolldown/src/utils/chunk/render_chunk_imports.rs#L107-L161

Need to think of way to handle external modules in iife format.

**Comment by underfin** [comment]
@hyf0  It panic because here has imports, if here remove panic, the user will meet a problem at executing it, because it will have unresolved symbols from imports. I would like panic way, the explicit error would be better than implicit error.

**Comment by hyf0** [comment]
> @hyf0 It panic because here has imports, if here remove panic, the user will meet a problem at executing it, because it will have unresolved symbols from imports. I would like panic way, the explicit error would be better than implicit error.

> the explicit error would be better than implicit error.

Panic with error message "App format doesn't need to generate imports" is not better at all.

The ideal way is first fixing the panic problem and then fix https://github.com/rolldown/rolldown/issues/1623.

**Comment by underfin** [comment]
Yeah. I get it. The vue package panic already fixed at https://github.com/oxc-project/oxc/pull/4268. The external module symbol not removed by dec. We could using better way to resolve it.

**Comment by hyf0** [comment]
I'm gonna merge this PR because it is not negative and not only a solution on panic of iife format but also a improvement on `render_preliminary_assets` function.

**Pull request merged**
