### PR TITLE
fix: use `citty` to detect if an argument is unspecified

### PR DESCRIPTION
**Pull request by Cecil0o0**
### Description

FIXME: `citty` doesn't support detecting if an argument is unspecified

### CODE REVIEW

**Comment by hyf0** [comment]
I'm confused how this PR fix the problem that motioned in the title. From my understanding, in this PR, there's no way to distinguish if user input `rolldown -c ""`  or `rolldown -c`.

**Comment by Cecil0o0** [comment]
@hyf0 Sorry I mis-understood this problem, for now, it still couldn't distinguish if user input `rolldown -c ""` or `rolldown -c`.

Let me try another solution

**Comment by Cecil0o0** [comment]
I have found a way to solve this problem, if we remove the `type` property of  `config` ArgsDef, `citty` would parse it to oneOf `string`, `boolean` and `number`, if so, we could distinguish that.

when user input `rolldown -c`, this arg would be `true`, and `rolldown -c ""` could be number `0`. Back to this situation, handling type `string` or `boolean` is enough.

could it be ok? @hyf0

**Comment by hyf0** [comment]
> I have found a way to solve this problem, if we remove the `type` property of `config` ArgsDef, `citty` would parse it to oneOf `string`, `boolean` and `number`, if so, we could distinguish that.
> 
> when user input `rolldown -c`, this arg would be `true`, and `rolldown -c ""` could be number `0`. Back to this situation, handling type `string` or `boolean` is enough.
> 
> could it be ok? @hyf0

I don't think it's better than the current solution. The best way to solve the problem is solving it in citty's repo. https://github.com/unjs/citty/issues/142

**Comment by Cecil0o0** [comment]
> > I have found a way to solve this problem, if we remove the `type` property of `config` ArgsDef, `citty` would parse it to oneOf `string`, `boolean` and `number`, if so, we could distinguish that.
> > when user input `rolldown -c`, this arg would be `true`, and `rolldown -c ""` could be number `0`. Back to this situation, handling type `string` or `boolean` is enough.
> > could it be ok? @hyf0
> 
> I don't think it's better than the current solution. The best way to solve the problem is solving it in citty's repo. [unjs/citty#142](https://github.com/unjs/citty/issues/142)

first code block:
https://github.com/unjs/citty/blob/0ea32b6c033839957744938f51dcf5b867d425e9/src/args.ts#L10-L43

second code block:
https://github.com/rolldown/rolldown/blob/8645e7782bd179ca1a261f5109ed32d7605ab8bd/packages/rolldown/src/cli/index.ts#L41

After I looked carefully at the two code blocks above, compare their logic that they describe. I thought that your code which uses `parseArgs` exported by `mri` without second param, may be equal to *not* to set `type` for `config` argument.

And maybe, it could just meet `mri`'s design, please look at the option description below:

image


by the way, have a good night!

**Pull request closed without merging**
