### PR TITLE
feat: normalize path for os

### LINKED ISSUE #2303: [Bug]: internal resolver does not normalize `\\` with `/`
### Reproduction link or steps

1. Download https://stackblitz.com/edit/github-6jajke-ay1vqe?file=README.md on Windows machine
2. Run `npm run build` and `npm run build:vite`
3. See the output difference

(An example output is written in README.md)

### What is expected?

Rolldown behaves the same with Vite (normalizes `\\` to `/`) or has a option to do that.

### What is actually happening?

Rolldown does not normalize `\\` to `/`.

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@351d2c7 => 0.13.2
```

### Any additional comments?

See https://vitejs.dev/guide/api-plugin.html#path-normalization.

Faced this while trying rolldown with Vite.

### PR DESCRIPTION
**Pull request by AliceLanniste**
### Description

close  #2303

I think` InputItem.name` should be `&str` type is better

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
Can you add some test?

**Comment by hyf0** [comment]
This only processed the input. https://github.com/rolldown/rolldown/issues/2303 is about normalizing all paths from `\\` to `/`.

We also need to define the behavior of  normalizing `\\` to `/`. When does `\\` would be treated as itself rather than a path separator. I'm ok with just converting every `\\` to `/`, just need to make sure it's expected.

**Comment by hyf0** [comment]
I just marked this PR on hold. The reason is in https://github.com/rolldown/rolldown/issues/2303#issuecomment-2386603980. Thanks for your PR. It pushed forward this issue to a end conclusion!

**Comment by hyf0** [comment]
Thanks for your attention on this part. Closed due to https://github.com/rolldown/rolldown/issues/2303#issuecomment-2386603980.

**Pull request closed without merging**
