### PR TITLE
chore(rust): fix typo

### PR DESCRIPTION
**Pull request by PengBoUESTC**
### Description

word spell check & update

### Test Plan

---

### CODE REVIEW

**Review by hyf0 — APPROVED** [review]
If you confirm there's no typos in the file, you could remove the top `cSpell:disable`

**Comment by PengBoUESTC** [comment]
> If you confirm there's no typos in the file, you could remove the top `cSpell:disable`

I will check it , and maybe a `_typos.toml` is needed to avoid rollup check in command `typos`

**Comment by hyf0** [comment]
I'm not sure I understand you. But we already have cSpell for checking typos and `cSpell.json` for customize words.

**Comment by PengBoUESTC** [comment]
> I'm not sure I understand you. But we already have cSpell for checking typos and `cSpell.json` for customize words.

I mean the `just check` command

**Comment by hyf0** [comment]
> > I'm not sure I understand you. But we already have cSpell for checking typos and `cSpell.json` for customize words.
> 
> I mean the `just check` command

Get it. Forget to remove it.

**Comment by PengBoUESTC** [comment]
> > > I'm not sure I understand you. But we already have cSpell for checking typos and `cSpell.json` for customize words.
> > 
> > 
> > I mean the `just check` command
> 
> Get it. Forget to remove it.

get it.

**Pull request merged**
