### PR TITLE
feat: support `output.hashCharacters`

### LINKED ISSUE #2646: [Feature Request]: Support `hashCharacters`
### What problem does this feature solve?

Base64 characters are sometimes visually difficult to tell apart, like 0O. [base36 and hex](https://rollupjs.org/configuration-options/#output-hashcharacters) are nicer human-readable alternatives.

### What does the proposed API look like?

`output.hashCharacters: "base64" | "base36" | "hex" = "base64"`

### PR DESCRIPTION
**Pull request by shulaoda**
### Description

closes #2646

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
The implementation did not seems right, 
```js
btoa('hello')
'aGVsbG8='
```

```rs
#[test]
fn test() {
  assert_eq!(xxhash_to_base_url(b"hello", 64), "aGVsbG8=");
  assert_eq!(to_standard_base64(b"hello"), "aGVsbG8=");
}
```
`xxhash_to_base_url` implementation will fail, `to_standard_base64` return correct output.

**Comment by shulaoda** [comment]
> `xxhash_to_base_url` implementation will fail, `to_standard_base64` return correct output.

In fact, it is not standard `base64`, but rather a `hash` computed using a specified base character set.

https://github.com/rolldown/rolldown/blob/063ad9dabe2a44be373f27df78179e8a750e44ba/crates/rolldown/src/utils/chunk/finalize_chunks.rs#L86-L87

Here, I actually referred to `Rollup`'s implementation but modified the order of the base character set to improve efficiency. See https://github.com/rollup/rollup/blob/master/rust/xxhash/src/lib.rs

**Comment by IWANABETHATGUY** [comment]
> > `xxhash_to_base_url` implementation will fail, `to_standard_base64` return correct output.
> 
> In fact, it is not standard `base64`, but rather a `hash` computed using a specified base character set.
> 
> https://github.com/rolldown/rolldown/blob/063ad9dabe2a44be373f27df78179e8a750e44ba/crates/rolldown/src/utils/chunk/finalize_chunks.rs#L86-L87
> 
> Here, I actually referred to `Rollup`'s implementation but modified the order of the base character set to improve efficiency. See https://github.com/rollup/rollup/blob/master/rust/xxhash/src/lib.rs

I think whatever efficiency you improve the output should be same, 

```rs
use base_encode::to_string;
use xxhash_rust::xxh3::xxh3_128;

const CHARACTERS_BASE64: &[u8; 64] =
    b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";

const CHARACTERS_BASE36: &[u8; 36] = b"abcdefghijklmnopqrstuvwxyz0123456789";

const CHARACTERS_BASE16: &[u8; 16] = b"abcdef0123456789";

pub fn xxhash_base64_url(input: &[u8]) -> String {
    to_string(input, 64, CHARACTERS_BASE64).unwrap()
}

const CHARACTERS: &[u8] = b"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_";

pub fn xxhash_with_base(hash: &[u8], base: u8) -> String {
    to_string(hash, base, &CHARACTERS[..base as usize]).unwrap()
}

pub fn xxhash_base36(input: &[u8]) -> String {
    to_string(&xxh3_128(input).to_le_bytes(), 36, CHARACTERS_BASE36).unwrap()
}

pub fn xxhash_base16(input: &[u8]) -> String {
    to_string(&xxh3_128(input).to_le_bytes(), 16, CHARACTERS_BASE16).unwrap()
}
fn main() {
    dbg!(&xxhash_base64_url(b"hello"));
    dbg!(&xxhash_with_base(b"hello", 64));
}

```

[src/main.rs:29:5] &xxhash_base64_url(b"hello") = "GhlbGxv"
[src/main.rs:30:5] &xxhash_with_base(b"hello", 64) = "6xBr6NL"

**Comment by IWANABETHATGUY** [comment]
Can you patch this?
```diff
diff --git a/crates/rolldown_utils/src/xxhash.rs b/crates/rolldown_utils/src/xxhash.rs
index 151b582ee..5473d881e 100644
--- a/crates/rolldown_utils/src/xxhash.rs
+++ b/crates/rolldown_utils/src/xxhash.rs
@@ -5,7 +5,10 @@ use xxhash_rust::xxh3::xxh3_128;
 
 use crate::base64::to_url_safe_base64;
 
-const CHARACTERS: &[u8] = b"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_";
+const CHARACTERS_BASE64: &[u8; 64] =
+  b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
+
+const CHARACTERS_BASE16: &[u8; 16] = b"abcdef0123456789";
 
 pub fn xxhash_base64_url(input: &[u8]) -> String {
   let hash = xxh3_128(input).to_le_bytes();
@@ -13,7 +16,20 @@ pub fn xxhash_base64_url(input: &[u8]) -> String {
 }
 
 pub fn xxhash_with_base(input: &[u8], base: u8) -> String {
-  let hash = if input.len() == 16 { input } else { &xxh3_128(input).to_le_bytes() };
+  let char_set = match base {
+    64 => CHARACTERS_BASE64,
+    36 => &CHARACTERS_BASE64[26..(26 + 36)],
+    16 => CHARACTERS_BASE16,
+    _ => {
+      unreachable!()
+    }
+  };
+  to_string(input, base, char_set).unwrap()
+}
 
-  to_string(hash, base, &CHARACTERS[..base as usize]).unwrap()
+#[test]
+fn test_xxhash_with_base() {
+  assert_eq!(&xxhash_with_base(b"hello", 64), "GhlbGxv");
+  assert_eq!(&xxhash_with_base(b"hello", 36), "fz9m294h");
+  assert_eq!(&xxhash_with_base(b"hello", 16), "020f060609");
 }
```

**Comment by IWANABETHATGUY** [comment]
I know you want to share same static string, but the order of the charset will affect the hash result.

**Comment by shulaoda** [comment]
> Can you patch this?

Yes, I am currently working on it. Running tests is too slow, and our ideas are almost identical!

**Review by IWANABETHATGUY — APPROVED** [review]

**Pull request merged**
