### PR TITLE
refactor: use macros to reduce duplicated codes in injection fields.

### PR DESCRIPTION
**Pull request by 7086cmd**
#### Introduction

This PR introduces several improvements and new features, focusing on code optimization and support for additional plugin functionalities.

#### Contents

1. **Code Optimization using Macros:**
    - Introduced macros to reduce duplicated code in `ecma_generator.rs`, specifically targeting the format renderers.
    - The `Plugin` trait is excluded from macro optimization due to an issue with async traits not being compatible with the macros.

2. **Plugin Enhancements:**
    - Added support for `intro` and `outro` in plugins, using #1713 as a reference example.

By utilizing macros, we've significantly reduced the amount of duplicated code, making the codebase cleaner and easier to maintain.

### CODE REVIEW

**Comment by hyf0** [comment]
Using macros is rejected. It's bad for maintaining.

**Comment by Boshen** [comment]
We try to avoid macros as much as we can. A macro should be used for DSLs or super repetitive work.

The usage here can be replicated by simple functions (I think).

**Comment by hyf0** [comment]
Yeah. Duplication isn't bad always. Introducing abstraction too early might be bad for future refactoring.

**Comment by 7086cmd** [comment]
I see. But the logic of these four is simply the same. I am wondering if there is a better way except for macros instead of copying them...?

**Pull request closed without merging**
