### PR TITLE
feat: bootstrap Rolldown with Rolldown

### PR DESCRIPTION
**Pull request by hyf0**
### Description

* The `rolldown` package published to npm is built with Rolldown
* TypeScript files are transpiled by esbuild via a plugin

### CODE REVIEW

**Comment by hyf0** [comment]
* **#1211** <a href="https://app.graphite.dev/github/pr/rolldown/rolldown/1211?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hyf0 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by hyf0** [comment]
Benchmark node failed due to large noise of github machines.

**Comment by Boshen** [comment]
dumb question: how do we verify the build is correct? Use the bootstrapped build to build some stuff?

**Comment by hyf0** [comment]
> dumb question: how do we verify the build is correct? Use the bootstrapped build to build some stuff?

It could be verified by rolldown and rollup's node tests. We will use self-bootstrapped rolldown to run all tests of rolldown and rollup's.

**Pull request merged**
