### PR TITLE
feat(wip): support `umd` format.

### PR DESCRIPTION
**Pull request by 7086cmd**
### Description

> Special thanks to @underfin for guiding the implementation of the `umd` support.

> This PR needs #1704 to be merged.

This PR introduces the integration of the `umd` format in Vite bundling. Notably, while `umd` supports `amd`, full support for `amd` has not been implemented yet and is not currently planned. An entry point for `amd` has been created, which will throw errors if attempted to use.

### Modifications

1. Added support for the `umd` format on both the node package and Rust side.
2. Implemented `render_umd` by reusing the `render_wrapper` function refactored in #1704. This function is instrumental in generating the wrapper function for SystemJS, AMD, UMD, and IIFE. Although support for SystemJS and AMD is not planned at this moment, it might be considered once stable.
3. Refactored `determine_export_mode` to ensure it is called only once.
4. **Note:** This PR is still a work in progress as tests have not yet been added. However, merging it now is not critical since `umd` format support is not a necessary part of this feature at the moment.

### CODE REVIEW

**Comment by hyf0** [comment]
`umd` is also not planned. Personally, I don't against merging this, but we don't have enough man power to maintain it. Even if it's merged, if it blocks some important refactor, related code and tests will be removed and ignored.

However, doing such thing is really a maintaining burden. I don't like to tell we aren't going to merge this. So please open a issue before rushing into a PR. We are also in the discord server, instant online chat is also welcome.

**Comment by 7086cmd** [comment]
OK, I see. There is no hurry to merge it now, I will keep marking it draft and modifying its content until we decide to support `umd` format. Shall I open the issue right now?

**Comment by hyf0** [comment]
Not needed.

**Comment by 7086cmd** [comment]
There are so many things that've changed these days. I'll rewrite it when we need UMD.

**Pull request closed without merging**
